Update createVM.yml

diff --git a/playbooks/createVM.yml b/playbooks/createVM.yml
--- a/playbooks/createVM.yml
+++ b/playbooks/createVM.yml
@@ -9,47 +9,67 @@
     - name: Debug vm_list
       debug:
         var: vm_list
-    # - name: Create VMs dynamically
-    #   community.vmware.vmware_guest:
-    #     hostname: "{{ vcenter.hostname }}"
-    #     username: "{{ vcenter.username }}"
-    #     password: "{{ vcenter.password }}"
-    #     validate_certs: "{{ validate_certs }}"
-    #     datacenter: "{{ datacenter.name }}"
-    #     cluster: "{{ datacenter.cluster }}"
-    #     folder: "{{ item.folder }}"
-    #     template: "{{ item.template }}"
-    #     name: "{{ item.name }}"
-    #     guest_id: "{{ item.guest_id }}"
-    #     state: "{{ item.state}}"
-    #     wait_for_ip_address: "{{ item.wait_for_ip_address }}"
-    #     hardware:
-    #       num_cpus: "{{ item.num_cpus }}"
-    #       memory_mb: "{{ item.memory_mb }}"
-    #     networks: "{{ item.networks }}"
-    #     disk: "{{ item.disk}}"
-    #     cdrom: "{{ item.cdrom}}"
-    #   loop: "{{ vm_details }}"
-    #   register: vm
-
- 
-    - name: Install VMware Tools on the VM
-      community.vmware.vmware_vm_shell:
+    - name: Create VMs dynamically
+      community.vmware.vmware_guest:
         hostname: "{{ vcenter.hostname }}"
         username: "{{ vcenter.username }}"
         password: "{{ vcenter.password }}"
+        validate_certs: "{{ validate_certs }}"
         datacenter: "{{ datacenter.name }}"
         cluster: "{{ datacenter.cluster }}"
         folder: "{{ item.folder }}"
-        vm_id: "{{ item.name }}"
-        vm_username: admin
-        vm_password: admin
-        vm_shell: "/bin/bash"
-        vm_shell_args:
-          - "systemctl status NetworkManger"
-        wait_for_process: true
-        timeout: 2000
+        template: "{{ item.template }}"
+        name: "{{ item.name }}"
+        guest_id: "{{ item.guest_id }}"
+        state: "{{ item.state}}"
+        wait_for_ip_address: "{{ item.wait_for_ip_address }}"
+        hardware:
+          num_cpus: "{{ item.num_cpus }}"
+          memory_mb: "{{ item.memory_mb }}"
+        networks: "{{ item.networks }}"
+        disk: "{{ item.disk}}"
+        cdrom: "{{ item.cdrom}}"
+        customization:
+          script_text: |
+            #!/bin/bash
+            # Install VMware Tools if not already installed
+            if ! dpkg -l | grep -q open-vm-tools; then
+              echo "Installing VMware Tools..."
+              apt-get update -y && apt-get install -y open-vm-tools
+            else
+              echo "VMware Tools already installed"
+            fi
+
+            # Restart VMware Tools service
+            systemctl restart open-vm-tools
+
+            # Verify VMware Tools is running
+            if systemctl is-active --quiet open-vm-tools; then
+              echo "VMware Tools is running"
+            else
+              echo "VMware Tools service failed to start"
+            fi
       loop: "{{ vm_details }}"
+      register: vm
+
+ 
+    # - name: Install VMware Tools on the VM
+    #   community.vmware.vmware_vm_shell:
+    #     hostname: "{{ vcenter.hostname }}"
+    #     username: "{{ vcenter.username }}"
+    #     password: "{{ vcenter.password }}"
+    #     datacenter: "{{ datacenter.name }}"
+    #     cluster: "{{ datacenter.cluster }}"
+    #     folder: "{{ item.folder }}"
+    #     vm_id: "{{ item.name }}"
+    #     vm_username: admin
+    #     vm_password: admin
+    #     vm_shell: "/bin/bash"
+    #     vm_shell_args:
+    #       - "systemctl status NetworkManger"
+    #     wait_for_process: true
+    #     timeout: 2000
+    #   loop: "{{ vm_details }}"
 
       
     # - name: Install or update the vm-tools
